<a href="https://colab.research.google.com/github/Sirilak-1447/229352-StatisticalLearning/blob/main/660510777_Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [472]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [473]:
a = torch.tensor(8)
b = torch.tensor(9)
print(a)
print(b)
print(a+b)

tensor(8)
tensor(9)
tensor(17)


### Convert a tensor to scalar

In [474]:
a.item()

8

### Creating 2D tensor

In [475]:
A = torch.tensor([[1, 2], [3, 4]])
print(A)

tensor([[1, 2],
        [3, 4]])


## Tensor and Numpy

### Convert from tensor to numpy array

In [476]:
A.numpy()

array([[1, 2],
       [3, 4]])

### Convert from numpy array to tensor

In [477]:
B = np.array([[1, 2], [3, 4]])

C = torch.from_numpy(B)
print(C)

tensor([[1, 2],
        [3, 4]])


## Basic operations

In [478]:
D = 2*C

E = C - 10

print(D)
print(E)

tensor([[2, 4],
        [6, 8]])
tensor([[-9, -8],
        [-7, -6]])


### Matrix multiplication

In [479]:
print(torch.matmul(D, E))
print(torch.mm(D, E))
print(D @ E)

tensor([[ -46,  -40],
        [-110,  -96]])
tensor([[ -46,  -40],
        [-110,  -96]])
tensor([[ -46,  -40],
        [-110,  -96]])


### Matrix transpose

In [480]:
print(C)
print( C.t() )

tensor([[1, 2],
        [3, 4]])
tensor([[1, 3],
        [2, 4]])


In [481]:
I = torch.tensor([[[1, 2],[3, 4]],[[5, 6],[7, 8]],[[-1, -2],[-3, -4]]])
print(I)
torch.transpose(I, 1, 2)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[-1, -2],
         [-3, -4]]])


tensor([[[ 1,  3],
         [ 2,  4]],

        [[ 5,  7],
         [ 6,  8]],

        [[-1, -3],
         [-2, -4]]])

## Creating a specific type of tensor

In [482]:
# print(torch.zeros(2,3))
# print(torch.ones(2,3))
# print(torch.rand(2,3))
# print(torch.randn(2,3))  # sample each number from N(0, 1)
# print(torch.arange(9))

In [483]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [484]:
torch.ones(2, 2, 2)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [485]:
torch.rand(2, 3)

tensor([[0.3128, 0.1793, 0.6928],
        [0.5915, 0.1419, 0.1707]])

In [486]:
torch.randn(3, 4) #มากกว่า -1 ได้น้อยกว่า 1 ได้

tensor([[ 0.6296, -0.6258,  1.0671, -0.4899],
        [ 1.1239, -1.1167, -1.9286, -0.2776],
        [ 0.2639, -1.4041,  1.7366,  0.7729]])

In [487]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Tensor's shape

### Checking the shape of a tensor

In [488]:
F = torch.zeros((4, 5))
print(F.shape)
print(F.size())

torch.Size([4, 5])
torch.Size([4, 5])


In [489]:
F = torch.zeros((2,4, 5))
F.shape

torch.Size([2, 4, 5])

In [490]:
F.shape[1]

4

In [491]:
F.size()

torch.Size([2, 4, 5])

### Changing the shape of a tensor

In [492]:
G = torch.arange(6)
print(G.view(2, 3))
print(G.reshape(2, 3))

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [493]:
G = torch.arange(6)
print(G.shape)

torch.Size([6])


In [494]:
G1 = G.reshape(2, 3)

G1

tensor([[0, 1, 2],
        [3, 4, 5]])

In [495]:
G2 = G.view(2, 3)

G2

tensor([[0, 1, 2],
        [3, 4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [496]:
H = torch.arange(6)
H1 = - torch.arange(6)

I = torch.stack([H, H1, H, H1], axis=0)
J = torch.stack([H, H1, H, H1], axis=1)
print(I)
print(J)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 0, -1, -2, -3, -4, -5],
        [ 0,  1,  2,  3,  4,  5],
        [ 0, -1, -2, -3, -4, -5]])
tensor([[ 0,  0,  0,  0],
        [ 1, -1,  1, -1],
        [ 2, -2,  2, -2],
        [ 3, -3,  3, -3],
        [ 4, -4,  4, -4],
        [ 5, -5,  5, -5]])


In [497]:
# # concatenate

# I = torch.cat([H, H, H, H], axis=0)
# print(I)
# H1 = torch.torch.tensor([[1, 2],[3, 4]])
# J = torch.cat([H, H, H, H], axis=1) # ไม่มีเเกนที่1
# print(J)

In [498]:
import torch

H = torch.tensor([[0, 1, 2], [3, 4, 5]])

# concat ตามแถว
I = torch.cat([H, H, H, H], dim=0)
print("Concatenate along dim=0:\n", I)

# concat ตามคอลัมน์
J = torch.cat([H, H, H, H], dim=1)
print("Concatenate along dim=1:\n", J)

Concatenate along dim=0:
 tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])
Concatenate along dim=1:
 tensor([[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5]])


### Squeezing a tensor (removing an extra dimension)

In [499]:
# [[1,2]] this is (1,2) tensor, want (2,)
print("H=", H) # shape = (6,)
K = H.reshape(1,6)
print("K=", K)
print(K.shape)

H= tensor([[0, 1, 2],
        [3, 4, 5]])
K= tensor([[0, 1, 2, 3, 4, 5]])
torch.Size([1, 6])


In [500]:
print(K.squeeze())

tensor([0, 1, 2, 3, 4, 5])


In [501]:
K1 = K.squeeze()

In [502]:
K1.shape

torch.Size([6])

In [503]:
H

tensor([[0, 1, 2],
        [3, 4, 5]])

In [504]:
H1.unsqueeze(axis=0)

tensor([[ 0, -1, -2, -3, -4, -5]])

In [505]:
H1.shape

torch.Size([6])

In [506]:
# H2.unsqueeze(axis=1)

In [507]:
# H2.shape

In [508]:
# H.shape = (6, )
L = H.unsqueeze(axis=0)  # L.shape(1, 6)
M = H.unsqueeze(axis=1)  # L.shape(6, 1)
print(L)
print(M)

tensor([[[0, 1, 2],
         [3, 4, 5]]])
tensor([[[0, 1, 2]],

        [[3, 4, 5]]])


## Indexing

In [509]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


## PyTorch and GPU

check if GPU is available

In [510]:
torch.cuda.is_available()

True

In [511]:
Q = torch.tensor([1, 2, 3])
print(Q.device)

cpu


In [512]:
R = Q.to('cuda')

R
print(Q.device)
print(R.device)

cpu
cuda:0


In [513]:
R.cpu().numpy()

array([1, 2, 3])

In [514]:
R1 = Q.cuda()

R1.device

device(type='cuda', index=0)

In [515]:
R.cpu().numpy()

array([1, 2, 3])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [516]:
torch.manual_seed(0)
np.random.seed(0)

**1.Create three random  𝑁(0,1)  tensors**

In [517]:
n, p = 200, 7
X_feat = torch.randn(200, 7)       # X.shape (200, 7)
b      = torch.randn(8, 1)         # b.shape (8, 1)
e      = torch.randn(200, 1)       # e.shape (200, 1)

**2.Create a tensor that contains only 1's with shape (200, 1)**

In [518]:
first = torch.ones(200, 1)

**3.Modify tensor X by adding the tensor in 2. as the first column**

In [519]:
X = torch.cat([first, X_feat], axis=1)

**4.Compute y**

In [520]:
y = X @ b + e
# y

**5.Fit a linear regression to the data X and y**

In [521]:
XtX_inv = torch.inverse(X.t() @ X)
b_hat = XtX_inv @ X.t() @ y

**6.Compute the predictions y_hat**

In [522]:
y_predic = X @ b_hat
# y_predic


**7.Convert both y and y_hat from tensor to Numpy array and calculate MSE**

In [523]:
y_np     = y.detach().cpu().numpy()
y_predic_np = y_predic.detach().cpu().numpy()
mse = float(((y_np - y_predic_np) ** 2).mean())

print("\nFirst 6 rows [y, y_predic]")
print(np.round(np.hstack([y_np[:6], y_predic_np[:6]]), 4))
print(f"\nMSE:{mse:}")


First 6 rows [y, y_predic]
[[-2.8974 -2.9538]
 [-1.8369 -0.8157]
 [-1.189  -0.8432]
 [-1.1544 -1.8438]
 [-1.0626 -0.366 ]
 [ 1.3811  1.7532]]

MSE:0.9451754093170166
